//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenAdsApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gradovi
    {
        public Gradovi()
        {
            this.Televizije = new HashSet<Televizije>();
        }
    
        public int GradID { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Televizije> Televizije { get; set; }
    }
}
