//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenAdsApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing
    {
        public int MarketingID { get; set; }
        public int PaketID { get; set; }
        public int ReklamaID { get; set; }
        public System.DateTime DatumOd { get; set; }
        public System.DateTime DatumDo { get; set; }
    
        public virtual Paketi Paketi { get; set; }
        public virtual Reklama Reklama { get; set; }
    }
}
