//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenAdsApi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class goldelec_screenAdsEntities1 : DbContext
    {
        public goldelec_screenAdsEntities1()
            : base("name=goldelec_screenAdsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Gradovi> Gradovi { get; set; }
        public DbSet<Klijenti> Klijenti { get; set; }
        public DbSet<Marketing> Marketing { get; set; }
        public DbSet<Objekti> Objekti { get; set; }
        public DbSet<Paketi> Paketi { get; set; }
        public DbSet<PaketiTelevizije> PaketiTelevizije { get; set; }
        public DbSet<PaketiTermini> PaketiTermini { get; set; }
        public DbSet<Reklama> Reklama { get; set; }
        public DbSet<Televizije> Televizije { get; set; }
        public DbSet<TipObjekta> TipObjekta { get; set; }
        public DbSet<CheckUpdateAndroid> CheckUpdateAndroid { get; set; }
        public DbSet<errorAndroid> errorAndroid { get; set; }
    
        public virtual int BrisiGrad(Nullable<int> gradID)
        {
            var gradIDParameter = gradID.HasValue ?
                new ObjectParameter("GradID", gradID) :
                new ObjectParameter("GradID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiGrad", gradIDParameter);
        }
    
        public virtual int BrisiKlijent(Nullable<int> klijentID)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiKlijent", klijentIDParameter);
        }
    
        public virtual int BrisiMarketing(Nullable<int> marketingID)
        {
            var marketingIDParameter = marketingID.HasValue ?
                new ObjectParameter("MarketingID", marketingID) :
                new ObjectParameter("MarketingID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiMarketing", marketingIDParameter);
        }
    
        public virtual int BrisiObjekat(Nullable<int> objekatID)
        {
            var objekatIDParameter = objekatID.HasValue ?
                new ObjectParameter("ObjekatID", objekatID) :
                new ObjectParameter("ObjekatID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiObjekat", objekatIDParameter);
        }
    
        public virtual int BrisiPaket(Nullable<int> paketID)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiPaket", paketIDParameter);
        }
    
        public virtual int BrisiPaketFromPaketiTelevizije(Nullable<int> paketID)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiPaketFromPaketiTelevizije", paketIDParameter);
        }
    
        public virtual int BrisiPaketiTermini(Nullable<int> paketID, string termin)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            var terminParameter = termin != null ?
                new ObjectParameter("Termin", termin) :
                new ObjectParameter("Termin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiPaketiTermini", paketIDParameter, terminParameter);
        }
    
        public virtual int BrisiPaketTelevizija(Nullable<int> paketTelevizijaID)
        {
            var paketTelevizijaIDParameter = paketTelevizijaID.HasValue ?
                new ObjectParameter("PaketTelevizijaID", paketTelevizijaID) :
                new ObjectParameter("PaketTelevizijaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiPaketTelevizija", paketTelevizijaIDParameter);
        }
    
        public virtual int BrisiReklamu(Nullable<int> reklamaID)
        {
            var reklamaIDParameter = reklamaID.HasValue ?
                new ObjectParameter("ReklamaID", reklamaID) :
                new ObjectParameter("ReklamaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiReklamu", reklamaIDParameter);
        }
    
        public virtual int BrisiTeleviziju(Nullable<int> televizijaID)
        {
            var televizijaIDParameter = televizijaID.HasValue ?
                new ObjectParameter("TelevizijaID", televizijaID) :
                new ObjectParameter("TelevizijaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiTeleviziju", televizijaIDParameter);
        }
    
        public virtual int BrisiTipObjekta(Nullable<int> tipID)
        {
            var tipIDParameter = tipID.HasValue ?
                new ObjectParameter("TipID", tipID) :
                new ObjectParameter("TipID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BrisiTipObjekta", tipIDParameter);
        }
    
        public virtual int DodajDane(Nullable<int> marketingID, Nullable<System.DateTime> dan)
        {
            var marketingIDParameter = marketingID.HasValue ?
                new ObjectParameter("MarketingID", marketingID) :
                new ObjectParameter("MarketingID", typeof(int));
    
            var danParameter = dan.HasValue ?
                new ObjectParameter("Dan", dan) :
                new ObjectParameter("Dan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajDane", marketingIDParameter, danParameter);
        }
    
        public virtual int DodajGrad(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajGrad", nazivParameter);
        }
    
        public virtual int DodajKlijent(string naziv, string kontaktTelefon, string kontaktOsoba)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var kontaktTelefonParameter = kontaktTelefon != null ?
                new ObjectParameter("KontaktTelefon", kontaktTelefon) :
                new ObjectParameter("KontaktTelefon", typeof(string));
    
            var kontaktOsobaParameter = kontaktOsoba != null ?
                new ObjectParameter("KontaktOsoba", kontaktOsoba) :
                new ObjectParameter("KontaktOsoba", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajKlijent", nazivParameter, kontaktTelefonParameter, kontaktOsobaParameter);
        }
    
        public virtual int DodajMarketing(Nullable<int> paketID, Nullable<int> reklamaID, Nullable<System.DateTime> datumOD, Nullable<System.DateTime> datumDO)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            var reklamaIDParameter = reklamaID.HasValue ?
                new ObjectParameter("ReklamaID", reklamaID) :
                new ObjectParameter("ReklamaID", typeof(int));
    
            var datumODParameter = datumOD.HasValue ?
                new ObjectParameter("DatumOD", datumOD) :
                new ObjectParameter("DatumOD", typeof(System.DateTime));
    
            var datumDOParameter = datumDO.HasValue ?
                new ObjectParameter("DatumDO", datumDO) :
                new ObjectParameter("DatumDO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajMarketing", paketIDParameter, reklamaIDParameter, datumODParameter, datumDOParameter);
        }
    
        public virtual int DodajObjekat(string adresa, string naziv, Nullable<int> tipObjektaID, string kontaktTelefon, string kontaktOsoba)
        {
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var tipObjektaIDParameter = tipObjektaID.HasValue ?
                new ObjectParameter("TipObjektaID", tipObjektaID) :
                new ObjectParameter("TipObjektaID", typeof(int));
    
            var kontaktTelefonParameter = kontaktTelefon != null ?
                new ObjectParameter("KontaktTelefon", kontaktTelefon) :
                new ObjectParameter("KontaktTelefon", typeof(string));
    
            var kontaktOsobaParameter = kontaktOsoba != null ?
                new ObjectParameter("KontaktOsoba", kontaktOsoba) :
                new ObjectParameter("KontaktOsoba", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajObjekat", adresaParameter, nazivParameter, tipObjektaIDParameter, kontaktTelefonParameter, kontaktOsobaParameter);
        }
    
        public virtual int DodajPaket(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajPaket", nazivParameter);
        }
    
        public virtual int DodajPaketiTelevizije(Nullable<int> paketID, Nullable<int> televizijaID)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            var televizijaIDParameter = televizijaID.HasValue ?
                new ObjectParameter("TelevizijaID", televizijaID) :
                new ObjectParameter("TelevizijaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajPaketiTelevizije", paketIDParameter, televizijaIDParameter);
        }
    
        public virtual int DodajPaketiTermini(Nullable<int> paketID, string termin)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            var terminParameter = termin != null ?
                new ObjectParameter("Termin", termin) :
                new ObjectParameter("Termin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajPaketiTermini", paketIDParameter, terminParameter);
        }
    
        public virtual int DodajReklamu(string naziv, string video, Nullable<int> klijentID, Nullable<int> duzina)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var videoParameter = video != null ?
                new ObjectParameter("Video", video) :
                new ObjectParameter("Video", typeof(string));
    
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            var duzinaParameter = duzina.HasValue ?
                new ObjectParameter("Duzina", duzina) :
                new ObjectParameter("Duzina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajReklamu", nazivParameter, videoParameter, klijentIDParameter, duzinaParameter);
        }
    
        public virtual int DodajTeleviziju(string naziv, Nullable<int> gradID, Nullable<int> objekatID)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var gradIDParameter = gradID.HasValue ?
                new ObjectParameter("GradID", gradID) :
                new ObjectParameter("GradID", typeof(int));
    
            var objekatIDParameter = objekatID.HasValue ?
                new ObjectParameter("ObjekatID", objekatID) :
                new ObjectParameter("ObjekatID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajTeleviziju", nazivParameter, gradIDParameter, objekatIDParameter);
        }
    
        public virtual int DodajTipObjekta(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DodajTipObjekta", nazivParameter);
        }
    
        public virtual ObjectResult<Info_Result> Info(Nullable<int> tvID, Nullable<System.DateTime> datum)
        {
            var tvIDParameter = tvID.HasValue ?
                new ObjectParameter("TvID", tvID) :
                new ObjectParameter("TvID", typeof(int));
    
            var datumParameter = datum.HasValue ?
                new ObjectParameter("Datum", datum) :
                new ObjectParameter("Datum", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Info_Result>("Info", tvIDParameter, datumParameter);
        }
    
        public virtual int IzmjeniObjekat(string adresa, string naziv, Nullable<int> tipObjektaID, Nullable<int> objekatID, string kontaktTelefon, string kontaktOsoba)
        {
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var tipObjektaIDParameter = tipObjektaID.HasValue ?
                new ObjectParameter("TipObjektaID", tipObjektaID) :
                new ObjectParameter("TipObjektaID", typeof(int));
    
            var objekatIDParameter = objekatID.HasValue ?
                new ObjectParameter("ObjekatID", objekatID) :
                new ObjectParameter("ObjekatID", typeof(int));
    
            var kontaktTelefonParameter = kontaktTelefon != null ?
                new ObjectParameter("KontaktTelefon", kontaktTelefon) :
                new ObjectParameter("KontaktTelefon", typeof(string));
    
            var kontaktOsobaParameter = kontaktOsoba != null ?
                new ObjectParameter("KontaktOsoba", kontaktOsoba) :
                new ObjectParameter("KontaktOsoba", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IzmjeniObjekat", adresaParameter, nazivParameter, tipObjektaIDParameter, objekatIDParameter, kontaktTelefonParameter, kontaktOsobaParameter);
        }
    
        public virtual int IzmjeniReklamu(Nullable<int> reklamaID, string naziv, Nullable<int> klijentID, string video)
        {
            var reklamaIDParameter = reklamaID.HasValue ?
                new ObjectParameter("ReklamaID", reklamaID) :
                new ObjectParameter("ReklamaID", typeof(int));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            var videoParameter = video != null ?
                new ObjectParameter("Video", video) :
                new ObjectParameter("Video", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IzmjeniReklamu", reklamaIDParameter, nazivParameter, klijentIDParameter, videoParameter);
        }
    
        public virtual int IzmjeniTeleviziju(Nullable<int> televizijaID, Nullable<int> gradID, Nullable<int> objekatID)
        {
            var televizijaIDParameter = televizijaID.HasValue ?
                new ObjectParameter("TelevizijaID", televizijaID) :
                new ObjectParameter("TelevizijaID", typeof(int));
    
            var gradIDParameter = gradID.HasValue ?
                new ObjectParameter("GradID", gradID) :
                new ObjectParameter("GradID", typeof(int));
    
            var objekatIDParameter = objekatID.HasValue ?
                new ObjectParameter("ObjekatID", objekatID) :
                new ObjectParameter("ObjekatID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IzmjeniTeleviziju", televizijaIDParameter, gradIDParameter, objekatIDParameter);
        }
    
        public virtual ObjectResult<KlijentByID_Result> KlijentByID(Nullable<int> klijentID)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KlijentByID_Result>("KlijentByID", klijentIDParameter);
        }
    
        public virtual ObjectResult<MarketingByReklama_Result> MarketingByReklama(Nullable<int> reklamaID)
        {
            var reklamaIDParameter = reklamaID.HasValue ?
                new ObjectParameter("ReklamaID", reklamaID) :
                new ObjectParameter("ReklamaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingByReklama_Result>("MarketingByReklama", reklamaIDParameter);
        }
    
        public virtual ObjectResult<MarketingKlijentPrikaz_Result> MarketingKlijentPrikaz(Nullable<int> klijentID)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingKlijentPrikaz_Result>("MarketingKlijentPrikaz", klijentIDParameter);
        }
    
        public virtual ObjectResult<MarketingProvjera_Result> MarketingProvjera(Nullable<int> paketID, Nullable<int> reklamaID, Nullable<System.DateTime> datumOD, Nullable<System.DateTime> datumDO)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("paketID", paketID) :
                new ObjectParameter("paketID", typeof(int));
    
            var reklamaIDParameter = reklamaID.HasValue ?
                new ObjectParameter("reklamaID", reklamaID) :
                new ObjectParameter("reklamaID", typeof(int));
    
            var datumODParameter = datumOD.HasValue ?
                new ObjectParameter("DatumOD", datumOD) :
                new ObjectParameter("DatumOD", typeof(System.DateTime));
    
            var datumDOParameter = datumDO.HasValue ?
                new ObjectParameter("DatumDO", datumDO) :
                new ObjectParameter("DatumDO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarketingProvjera_Result>("MarketingProvjera", paketIDParameter, reklamaIDParameter, datumODParameter, datumDOParameter);
        }
    
        public virtual ObjectResult<ObjekatByID_Result> ObjekatByID(Nullable<int> objekatID)
        {
            var objekatIDParameter = objekatID.HasValue ?
                new ObjectParameter("ObjekatID", objekatID) :
                new ObjectParameter("ObjekatID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObjekatByID_Result>("ObjekatByID", objekatIDParameter);
        }
    
        public virtual ObjectResult<ObjekatByNaziv_Result> ObjekatByNaziv(string objekatNaziv)
        {
            var objekatNazivParameter = objekatNaziv != null ?
                new ObjectParameter("ObjekatNaziv", objekatNaziv) :
                new ObjectParameter("ObjekatNaziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObjekatByNaziv_Result>("ObjekatByNaziv", objekatNazivParameter);
        }
    
        public virtual ObjectResult<ObjektiSaTipovima_Result> ObjektiSaTipovima()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObjektiSaTipovima_Result>("ObjektiSaTipovima");
        }
    
        public virtual int ObrisiTvByObjekat(Nullable<int> objekatID)
        {
            var objekatIDParameter = objekatID.HasValue ?
                new ObjectParameter("ObjekatID", objekatID) :
                new ObjectParameter("ObjekatID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ObrisiTvByObjekat", objekatIDParameter);
        }
    
        public virtual int ObrišiTvFromPaketiTelevizije(Nullable<int> televizijaID)
        {
            var televizijaIDParameter = televizijaID.HasValue ?
                new ObjectParameter("TelevizijaID", televizijaID) :
                new ObjectParameter("TelevizijaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ObrišiTvFromPaketiTelevizije", televizijaIDParameter);
        }
    
        public virtual ObjectResult<PaketByName_Result> PaketByName(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaketByName_Result>("PaketByName", nazivParameter);
        }
    
        public virtual ObjectResult<PaketInfo_Result> PaketInfo(Nullable<int> paketID)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaketInfo_Result>("PaketInfo", paketIDParameter);
        }
    
        public virtual ObjectResult<PaketiTelevizijeByPaketIDTelevizijaID_Result> PaketiTelevizijeByPaketIDTelevizijaID(Nullable<int> paketID, Nullable<int> televizijaID)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            var televizijaIDParameter = televizijaID.HasValue ?
                new ObjectParameter("TelevizijaID", televizijaID) :
                new ObjectParameter("TelevizijaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaketiTelevizijeByPaketIDTelevizijaID_Result>("PaketiTelevizijeByPaketIDTelevizijaID", paketIDParameter, televizijaIDParameter);
        }
    
        public virtual ObjectResult<PaketiTerminiProvjera_Result> PaketiTerminiProvjera(Nullable<int> paketID, string termin)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            var terminParameter = termin != null ?
                new ObjectParameter("Termin", termin) :
                new ObjectParameter("Termin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaketiTerminiProvjera_Result>("PaketiTerminiProvjera", paketIDParameter, terminParameter);
        }
    
        public virtual ObjectResult<ProvjeraSlobodnihDana_Result> ProvjeraSlobodnihDana(Nullable<int> paketID, Nullable<System.DateTime> dan)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("PaketID", paketID) :
                new ObjectParameter("PaketID", typeof(int));
    
            var danParameter = dan.HasValue ?
                new ObjectParameter("Dan", dan) :
                new ObjectParameter("Dan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProvjeraSlobodnihDana_Result>("ProvjeraSlobodnihDana", paketIDParameter, danParameter);
        }
    
        public virtual ObjectResult<ReklamaByID_Result> ReklamaByID(Nullable<int> reklamaID)
        {
            var reklamaIDParameter = reklamaID.HasValue ?
                new ObjectParameter("ReklamaID", reklamaID) :
                new ObjectParameter("ReklamaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReklamaByID_Result>("ReklamaByID", reklamaIDParameter);
        }
    
        public virtual ObjectResult<ReklamaByNaziv_Result> ReklamaByNaziv(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReklamaByNaziv_Result>("ReklamaByNaziv", nazivParameter);
        }
    
        public virtual ObjectResult<ReklameByKlijent_Result> ReklameByKlijent(Nullable<int> klijentID)
        {
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReklameByKlijent_Result>("ReklameByKlijent", klijentIDParameter);
        }
    
        public virtual ObjectResult<SveReklame_Result> SveReklame()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SveReklame_Result>("SveReklame");
        }
    
        public virtual ObjectResult<SveTelevizije_Result> SveTelevizije()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SveTelevizije_Result>("SveTelevizije");
        }
    
        public virtual ObjectResult<SviGradovi_Result> SviGradovi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SviGradovi_Result>("SviGradovi");
        }
    
        public virtual ObjectResult<SviKlijenti_Result> SviKlijenti()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SviKlijenti_Result>("SviKlijenti");
        }
    
        public virtual ObjectResult<SviObjekti_Result> SviObjekti()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SviObjekti_Result>("SviObjekti");
        }
    
        public virtual ObjectResult<SviPaketi_Result> SviPaketi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SviPaketi_Result>("SviPaketi");
        }
    
        public virtual ObjectResult<SviTipoviObjekta_Result> SviTipoviObjekta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SviTipoviObjekta_Result>("SviTipoviObjekta");
        }
    
        public virtual ObjectResult<TelevizijaByID_Result> TelevizijaByID(Nullable<int> televizijaID)
        {
            var televizijaIDParameter = televizijaID.HasValue ?
                new ObjectParameter("TelevizijaID", televizijaID) :
                new ObjectParameter("TelevizijaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TelevizijaByID_Result>("TelevizijaByID", televizijaIDParameter);
        }
    
        public virtual ObjectResult<TelevizijaByName_Result> TelevizijaByName(string nazivTV)
        {
            var nazivTVParameter = nazivTV != null ?
                new ObjectParameter("NazivTV", nazivTV) :
                new ObjectParameter("NazivTV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TelevizijaByName_Result>("TelevizijaByName", nazivTVParameter);
        }
    
        public virtual ObjectResult<TelevizijeByPaket_Result> TelevizijeByPaket(Nullable<int> paketID)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("paketID", paketID) :
                new ObjectParameter("paketID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TelevizijeByPaket_Result>("TelevizijeByPaket", paketIDParameter);
        }
    
        public virtual ObjectResult<TelevizijeInfo_Result> TelevizijeInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TelevizijeInfo_Result>("TelevizijeInfo");
        }
    
        public virtual ObjectResult<TerminiByPaket_Result> TerminiByPaket(Nullable<int> paketID)
        {
            var paketIDParameter = paketID.HasValue ?
                new ObjectParameter("paketID", paketID) :
                new ObjectParameter("paketID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TerminiByPaket_Result>("TerminiByPaket", paketIDParameter);
        }
    
        public virtual ObjectResult<TipOBjektaByName_Result> TipOBjektaByName(string tipOBjekta)
        {
            var tipOBjektaParameter = tipOBjekta != null ?
                new ObjectParameter("TipOBjekta", tipOBjekta) :
                new ObjectParameter("TipOBjekta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TipOBjektaByName_Result>("TipOBjektaByName", tipOBjektaParameter);
        }
    
        public virtual int UpdateAndroidDodaj(Nullable<int> number)
        {
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAndroidDodaj", numberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UPDATEANDROIDTRENUTNISTATUS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UPDATEANDROIDTRENUTNISTATUS");
        }
    
        public virtual int DeleteError(Nullable<int> errorID)
        {
            var errorIDParameter = errorID.HasValue ?
                new ObjectParameter("errorID", errorID) :
                new ObjectParameter("errorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteError", errorIDParameter);
        }
    
        public virtual int InsertError(string nazivTV, Nullable<System.DateTime> vrijeme, string tipErrora)
        {
            var nazivTVParameter = nazivTV != null ?
                new ObjectParameter("NazivTV", nazivTV) :
                new ObjectParameter("NazivTV", typeof(string));
    
            var vrijemeParameter = vrijeme.HasValue ?
                new ObjectParameter("Vrijeme", vrijeme) :
                new ObjectParameter("Vrijeme", typeof(System.DateTime));
    
            var tipErroraParameter = tipErrora != null ?
                new ObjectParameter("TipErrora", tipErrora) :
                new ObjectParameter("TipErrora", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertError", nazivTVParameter, vrijemeParameter, tipErroraParameter);
        }
    
        public virtual ObjectResult<SelectError_Result> SelectError()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectError_Result>("SelectError");
        }
    
        public virtual ObjectResult<UpdateError_Result> UpdateError(string nazivTV, string tipErrora, Nullable<System.DateTime> vrijeme)
        {
            var nazivTVParameter = nazivTV != null ?
                new ObjectParameter("NazivTV", nazivTV) :
                new ObjectParameter("NazivTV", typeof(string));
    
            var tipErroraParameter = tipErrora != null ?
                new ObjectParameter("TipErrora", tipErrora) :
                new ObjectParameter("TipErrora", typeof(string));
    
            var vrijemeParameter = vrijeme.HasValue ?
                new ObjectParameter("Vrijeme", vrijeme) :
                new ObjectParameter("Vrijeme", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateError_Result>("UpdateError", nazivTVParameter, tipErroraParameter, vrijemeParameter);
        }
    
        public virtual ObjectResult<SelectErrorUpdateProvjera_Result> SelectErrorUpdateProvjera(string tV, Nullable<System.DateTime> vrijeme, string tiperrora)
        {
            var tVParameter = tV != null ?
                new ObjectParameter("TV", tV) :
                new ObjectParameter("TV", typeof(string));
    
            var vrijemeParameter = vrijeme.HasValue ?
                new ObjectParameter("Vrijeme", vrijeme) :
                new ObjectParameter("Vrijeme", typeof(System.DateTime));
    
            var tiperroraParameter = tiperrora != null ?
                new ObjectParameter("Tiperrora", tiperrora) :
                new ObjectParameter("Tiperrora", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectErrorUpdateProvjera_Result>("SelectErrorUpdateProvjera", tVParameter, vrijemeParameter, tiperroraParameter);
        }
    }
}
