//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenAdsApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklama
    {
        public Reklama()
        {
            this.Marketing = new HashSet<Marketing>();
        }
    
        public int ReklamaID { get; set; }
        public string Video { get; set; }
        public int KlijentID { get; set; }
        public string Naziv { get; set; }
        public int DuzinaReklame { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        public virtual ICollection<Marketing> Marketing { get; set; }
    }
}
