//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenAdsApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Televizije
    {
        public Televizije()
        {
            this.PaketiTelevizije = new HashSet<PaketiTelevizije>();
        }
    
        public int TelevizijaID { get; set; }
        public string Naziv { get; set; }
        public int GradID { get; set; }
        public int ObjekatId { get; set; }
    
        public virtual Gradovi Gradovi { get; set; }
        public virtual Objekti Objekti { get; set; }
        public virtual ICollection<PaketiTelevizije> PaketiTelevizije { get; set; }
    }
}
